### ISSUE TITLE
Name of repo is too generic, it's hard to find the project

### ISSUE THREAD

**Issue by ghost** [frno7/linux#36]
I'd suggest something like linux-ps2.

**Comment by frno7** [comment]
What search engines did you try? I tried GitHub’s and it appears to have difficulties, even though we do have a `ps2` topic tag. 

General search engines on the internet tend to use algorithms such as [page rank](https://en.wikipedia.org/wiki/PageRank), which scores pages according to the number of links to them: few links means low rank and little importance.

**Comment by ghost** [comment]
I tried to use popular search engines, but most of them point to pages of about official Linux for ps2. It's hard to find something which has name similar to something bigger.

**Comment by frno7** [comment]
Yes, words such as `linux` and `ps2` are extremely common, with links pointing everywhere. This repository was made for the Linux architectures that I use. There are several of them, after all. As it happens, the PlayStation 2 port is the largest in terms of patches, so far. :)
