### ISSUE TITLE
Question: Networking, Gentoo live USB

### ISSUE THREAD

**Issue by JohnShiozo** [frno7/linux#86]
Does network work now? also the Gentoo live USB download link is dead so idk if you could update it with a new build

**Comment by AKuHAK** [comment]
Network works just fine from usb dongle. As about LiveUSb, that image iant maintained by repository owner.

**Comment by frno7** [comment]
As @AKuHAK noted, networking can be made to work with a suitable USB device. Both wifi and ethernet, but some devices (especially wifi) require more USB memory than is available on the PlayStation 2. Issue #19 is about making use of PlayStation 2 network hardware, both built-in and attached via the expansion bay.

**Comment by JohnShiozo** [comment]
Thank you
